[versions]
agp = "8.10.1"
kotlin = "1.9.25"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
composeBom = "2025.08.01"
lifecycleViewModelCompose = "2.9.3"
navigationCompose = "2.9.3"
runtimeCompose = "2.9.3"
coroutines = "1.7.3"
retrofit = "2.9.0"
okhttp = "4.12.0"
hilt = "2.52"
hiltNavigationCompose = "1.2.0"
datastore = "1.0.0"
testExtJunit = "1.1.5"
espresso = "3.5.1"
zxingCore = "3.5.3"
zxingEmbedded = "4.3.0"
permissionsCompose = "0.0.1+4"
coil = "2.6.0"
lottie = "6.0.0"
accompanist-webview = "0.34.0"
camerax = "1.3.4"
mlkit-barcode = "17.2.0"
dynamic-toasts = "4.3.0"
accompanist = "0.31.5-beta"
nearpay-sdk-store = "2.1.88"
work-runtime-ktx = "2.8.1"
process-phoenix = "2.1.2"
material3 = "1.3.1"
usb-serial = "3.10.0"
kotlinx-serialization-json = "1.5.1"
jose4j = "0.9.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "runtimeCompose" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testExtJunit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingEmbedded" }

permissions-compose = { group = "com.meticha", name = "permissions_compose", version.ref = "permissionsCompose" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist-webview" }

camerax-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }

mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode" }
dynamic-toasts = { group = "com.pranavpandey.android", name = "dynamic-toasts", version.ref = "dynamic-toasts" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
nearpay-sdk-store = { module = "io.nearpay:nearpay-sdk-store", version.ref = "nearpay-sdk-store" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "process-phoenix" }

usb-serial-android = { module = "com.github.mik3y:usb-serial-for-android", version.ref = "usb-serial" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
maybank-ecr-sdk = { module = "com.itbizflow:ecrsdkhelper", version = "1.0.0-003" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version = "1.1.0-alpha06" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }